### ISSUE TITLE
wait_for_completion option

### ISSUE THREAD

**Issue by PnPie** [codelibs/elasticsearch-reindexing#27]
Could you please take a look at the "wait_for_completion" option because it seems for me that it doesn't really "wait" for execution, and we only use it when the anonymous `ActionListener<Void>`'s `onResponse` Method in `ReindexRestAction.java` get called, but at that time we have already finished the scroll search and the reindexing buld request:
```
ReindexingService.java (ReindexingService.ReindexingListener#onResponse(SearchResponse)):
if (hits.length == 0) {
    scrollId = null;
    reindexingListenerMap.remove(name);
    listener.onResponse(null);
}
```
So this boolean value just determined that if we send response or not for client rest request and put it in the hashmap or not ?

Sincerely,
Yu

**Comment by marevol** [comment]
I could not understand your problem...

If wait_for_completion is true, a response is returned in onResponse of reindexingService.
(Client needs to ignore a request timeout.)

If wait_for_completion is false, a response is returned immediately at:
https://github.com/codelibs/elasticsearch-reindexing/blob/master/src/main/java/org/codelibs/elasticsearch/reindex/rest/ReindexRestAction.java#L92
sendResponse method in onResponse of reindexingService is ignored.

Therefore, I think wait_for_completion is expected behavior.

**Comment by PnPie** [comment]
I'm really sorry I just made a mistake, it was totally right.
